#!/bin/bash
SOURCE_HESTIACP_USER="robomart";
SOURCE_HESTIACP_USER_DOMAIN="robomart.com";
SOURCE_HESTIACP_USER_DOMAIN_DATABASE_NAME="robomart_v3";
SOURCE_HESTIACP_USER_DOMAIN_DATABASE_USER="robomart_v3_dev_backup_user";
SOURCE_HESTIACP_USER_DOMAIN_DATABASE_PASSWORD="ok8gdnd387GC@D26dl";
TARGET_HESTIACP_USER="robomart-dev-01";
TARGET_HESTIACP_USER_DOMAIN="dev-01.robomart.com";
TARGET_HESTIACP_USER_DOMAIN_DATABASE_NAME="robomart_dev_01";
TARGET_HESTIACP_USER_DOMAIN_DATABASE_USER="robomart-dev-01-web";
TARGET_HESTIACP_USER_DOMAIN_DATABASE_PASSWORD="ok8gdnd387GC@D26dl";
TEMP_CONFIG_BACKUP_DIR="/home/robomart-dev-backup-temp-dir";
echo `date +"%Y-%m-%d %T"`  "removeing any previous backup configs";
rm -rf $TEMP_CONFIG_BACKUP_DIR/$TARGET_HESTIACP_USER;
echo `date +"%Y-%m-%d %T"`  "creating directory to store live dev versions configs"
mkdir -p $TEMP_CONFIG_BACKUP_DIR/$TARGET_HESTIACP_USER/admin;
echo `date +"%Y-%m-%d %T"`  "backuping config file";
cp /home/$TARGET_HESTIACP_USER/web/$TARGET_HESTIACP_USER_DOMAIN/public_html/config.php $TEMP_CONFIG_BACKUP_DIR/$TARGET_HESTIACP_USER/;
echo `date +"%Y-%m-%d %T"`  "backuping robots.txt file";
cp /home/$TARGET_HESTIACP_USER/web/$TARGET_HESTIACP_USER_DOMAIN/public_html/robots.txt $TEMP_CONFIG_BACKUP_DIR/$TARGET_HESTIACP_USER/;
echo `date +"%Y-%m-%d %T"`  "backuping admin config file";
cp /home/$TARGET_HESTIACP_USER/web/$TARGET_HESTIACP_USER_DOMAIN/public_html/admin/config.php $TEMP_CONFIG_BACKUP_DIR/$TARGET_HESTIACP_USER/admin/;
echo `date +"%Y-%m-%d %T"`  "removing current dev public_html dir";
rm -rf /home/$TARGET_HESTIACP_USER/web/$TARGET_HESTIACP_USER_DOMAIN/public_html/*;
echo `date +"%Y-%m-%d %T"`  "removing current dev storage dir";
rm -rf /home/$TARGET_HESTIACP_USER/web/$TARGET_HESTIACP_USER_DOMAIN/storage/*;
echo `date +"%Y-%m-%d %T"`  "copying live robomart public_html dir to dev_version public_html";
cp -r /home/$SOURCE_HESTIACP_USER/web/$SOURCE_HESTIACP_USER_DOMAIN/public_html/* /home/$TARGET_HESTIACP_USER/web/$TARGET_HESTIACP_USER_DOMAIN/public_html/;
echo `date +"%Y-%m-%d %T"`  "copying live robomart storage dir to dev_version storage dir";
cp -r /home/$SOURCE_HESTIACP_USER/web/$SOURCE_HESTIACP_USER_DOMAIN/storage/* /home/$TARGET_HESTIACP_USER/web/$TARGET_HESTIACP_USER_DOMAIN/storage/;
echo `date +"%Y-%m-%d %T"`  "taking live robomart mysql database backup";
mysqldump -u$SOURCE_HESTIACP_USER_DOMAIN_DATABASE_USER -p$SOURCE_HESTIACP_USER_DOMAIN_DATABASE_PASSWORD --no-create-db --single-transaction $SOURCE_HESTIACP_USER_DOMAIN_DATABASE_NAME  | gzip > $TEMP_CONFIG_BACKUP_DIR/$TARGET_HESTIACP_USER/robomart_db.sql.gz;
echo `date +"%Y-%m-%d %T"`  "droping dev_version database";
mysql -u$TARGET_HESTIACP_USER_DOMAIN_DATABASE_USER -p$TARGET_HESTIACP_USER_DOMAIN_DATABASE_PASSWORD -e "drop database $TARGET_HESTIACP_USER_DOMAIN_DATABASE_NAME";
echo `date +"%Y-%m-%d %T"`  "creating dev_version database";
mysql -u$TARGET_HESTIACP_USER_DOMAIN_DATABASE_USER -p$TARGET_HESTIACP_USER_DOMAIN_DATABASE_PASSWORD -e "CREATE DATABASE $TARGET_HESTIACP_USER_DOMAIN_DATABASE_NAME CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci";
echo `date +"%Y-%m-%d %T"`  "importing live robomart site database to dev_version database";
zcat $TEMP_CONFIG_BACKUP_DIR/$TARGET_HESTIACP_USER/robomart_db.sql.gz | pv | mysql -u$TARGET_HESTIACP_USER_DOMAIN_DATABASE_USER -p$TARGET_HESTIACP_USER_DOMAIN_DATABASE_PASSWORD --database=$TARGET_HESTIACP_USER_DOMAIN_DATABASE_NAME;
echo `date +"%Y-%m-%d %T"`  "copying previous backedup dev_version config to live dev_version config";
cp -f $TEMP_CONFIG_BACKUP_DIR/$TARGET_HESTIACP_USER/config.php /home/$TARGET_HESTIACP_USER/web/$TARGET_HESTIACP_USER_DOMAIN/public_html/;
echo `date +"%Y-%m-%d %T"`  "copying previous backedup dev_version robots.txt to live dev_version robots.txt";
cp -f $TEMP_CONFIG_BACKUP_DIR/$TARGET_HESTIACP_USER/robots.txt /home/$TARGET_HESTIACP_USER/web/$TARGET_HESTIACP_USER_DOMAIN/public_html/;
echo `date +"%Y-%m-%d %T"`  "copying previous backedup dev_version admin config to live dev_version admin config";
cp -f $TEMP_CONFIG_BACKUP_DIR/$TARGET_HESTIACP_USER/admin/config.php /home/$TARGET_HESTIACP_USER/web/$TARGET_HESTIACP_USER_DOMAIN/public_html/admin/;
echo `date +"%Y-%m-%d %T"`  "restoring permission to live dev_version public_html dir";
chown -R $TARGET_HESTIACP_USER:$TARGET_HESTIACP_USER /home/$TARGET_HESTIACP_USER/web/$TARGET_HESTIACP_USER_DOMAIN/public_html/*;
echo `date +"%Y-%m-%d %T"`  "restoring permission to live dev_version storage dir";
chown -R $TARGET_HESTIACP_USER:$TARGET_HESTIACP_USER /home/$TARGET_HESTIACP_USER/web/$TARGET_HESTIACP_USER_DOMAIN/storage/*;
echo `date +"%Y-%m-%d %T"`  "Dev Backup Created";
